
# config/config.yaml
data:
  url: "https://storage.googleapis.com/covid19-open-data/v3/latest/aggregated.csv"
  file_name: "covid19.csv"
  dbfs_path: "/mnt/ntconsult"

# Caminhos para as camadas de arquitetura Medallion
paths:
  raw: "/mnt/ntconsult/raw"
  bronze: "/mnt/ntconsult/bronze"
  silver: "/mnt/ntconsult/silver"
  gold: "/mnt/ntconsult/gold"

# Outras configurações que podem ser úteis para o pipeline
etl:
  batch_size: 10000
  retries: 3
